# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c2c0c3b34b525648c95102686238e28aafde26de2322387cfc8170ff63a79821ed49873f9e7c9a4c0400fdd54ccc98a38dd72dc634d76c1fa17a2970028bd0f

test:
  secret_key_base: aa9aa832f9d73c26ed89d126dce75fba273bab3ffe4d508703b4e3e82c2ea4aef8517429bc1d772b92e14069e8b855e9f4d5106074596b7726b52f34d28a9815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
